USE [$(CastleBlack)]

BEGIN TRAN
                TRUNCATE TABLE [$(CastleBlack)].[NIghtsWatch].[Checklists]
COMMIT TRAN

BEGIN TRAN --INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'',N'')

		--New Implementation or Base Build
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'New Implementation or Base Build',N'Typo or spelling error')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'New Implementation or Base Build',N'Error in functionality for making a report, asking a question')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'New Implementation or Base Build',N'Incorrect data privacy flow or restrictions')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'New Implementation or Base Build',N'Error in locking of locations on the issue package')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'New Implementation or Base Build',N'Error in use of PSO instructions with regard to locking locations ')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'New Implementation or Base Build',N'Incorrect attachment')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'New Implementation or Base Build',N'Incorrect phone number based on TOW (Telephony Order Form) attachment in SalesForce (if mentioned in case)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'New Implementation or Base Build',N'Incorrect package on child tier (if relevant). If not copied to children, failed to add note in PSO instructions explaining why children have different package than parent.')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'New Implementation or Base Build',N'Incorrect screen pop greeting compared to greeting in workbook')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'New Implementation or Base Build',N'Follow up link or form did not have full path (for European server clients)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'New Implementation or Base Build',N'Monetary value questions are inconsistent or non-functional')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'New Implementation or Base Build',N'Developer used incorrect template')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'New Implementation or Base Build',N'Browser - Checked in Firefox')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'New Implementation or Base Build',N'Browser - Checked in Chrome')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'New Implementation or Base Build',N'Browser - Checked in IE11')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'New Implementation or Base Build',N'Browser - Checked in IE10')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'New Implementation or Base Build',N'Browser - Checked in IE9')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'New Implementation or Base Build',N'Browser - Checked in IE8')
																																																																														
		--Attachments                                                                                                                                                                                                                                                                                                  
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Attachments',N'Incorrect nav bar links')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Attachments',N'Incorrect body text embedded links')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Attachments',N'Attachment when checked from live link was incorrect')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Attachments',N'"Leaving EP" interim page missing for attachments to external resources')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Attachments',N'Attachment update not correct for all languages')

		--Web  Site Text Edit – English
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web  Site Text Edit - English',N'Incorrect edit')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web  Site Text Edit - English',N'Typo introduced by edit')
		--Web Site Text Edit - non-English
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Text Edit - non-English',N'Incorrect edit')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Text Edit - non-English',N'Typo introduced by edit')
		--Web Site Edits to Functionality or Look and Feel
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Edits to Functionality or Look and Feel',N'Edit did not match request')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Edits to Functionality or Look and Feel',N'Edit introduced script error')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Edits to Functionality or Look and Feel',N'Edit introduced display issue')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Edits to Functionality or Look and Feel',N'Browser - Checked in Firefox')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Edits to Functionality or Look and Feel',N'Browser - Checked in Chrome')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Edits to Functionality or Look and Feel',N'Browser - Checked in IE11')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Edits to Functionality or Look and Feel',N'Browser - Checked in IE10')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Edits to Functionality or Look and Feel',N'Browser - Checked in IE9')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Edits to Functionality or Look and Feel',N'Browser - Checked in IE8')
		--Screen Pop / Contact Center Intake Site Text
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Screen Pop / Contact Center Intake Site Text',N'Error in flow from screen-pop to reporting page (most common is jump from CC to English)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Screen Pop / Contact Center Intake Site Text',N'Did not provide links to screen pops in SF case. Should provide links to all screen pops affected or indicate all pops were modified and provide link to example')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Screen Pop / Contact Center Intake Site Text',N'Edits made to some screen pops but not all which should have been modified.')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Screen Pop / Contact Center Intake Site Text',N'Made edits to screen pop when they should have been made to contact center portal')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Screen Pop / Contact Center Intake Site Text',N'Browser - Checked in Firefox')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Screen Pop / Contact Center Intake Site Text',N'Browser - Checked in Chrome')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Screen Pop / Contact Center Intake Site Text',N'Browser - Checked in IE11')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Screen Pop / Contact Center Intake Site Text',N'Browser - Checked in IE10')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Screen Pop / Contact Center Intake Site Text',N'Browser - Checked in IE9')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Screen Pop / Contact Center Intake Site Text',N'Browser - Checked in IE8')
		--Locations
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'DP country not flagged for DP')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Country name typo')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Country name forms inconsistent (abbreviations)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Country name forms inconsistent (translations)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Country field missing for DP client')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Countries flagged differently for DP')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Country in LDB not in ciClientVars.js')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'State field missing for country needing state')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Inconsistency in state names (form) - same state')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Inconsistency in state names (form) - different states')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'State name typo')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'REDIRECTCLIENTID does not belong to client')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Dropped leading zeros in zip codes')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Data exceeds character limits for field (see guide in Confluence)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'For an initial LDB upload, flow shows issue selection before location selection indicating "Location is selected before violation type" was not checked for all tiers. ')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Number of locations in LDB does not match number in spreadsheet AND no comment was made in the case explaining the mismatch')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Display does not match fields in data')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Locationid not passed so  fields are not filled on the reporting page.')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Inconsistent City / State / Country names: Ft. Worth vs Fort Worth')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Mismatch in DP flagging between LDB and scripts')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Error in locking of locations on the issue package')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Error in use of PSO instructions with regard to locking locations ')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Locations duplicated in LDB')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Locations duplicated based on dropdowns used to filter location data')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Data in LDB in incorrect field')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Column or field missed in upload')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Did not list location fields used before and after the update in the SF case')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Missed update to "CI_client.dropDowns.data" so error custom routing ')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Browser - Checked in Firefox')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Browser - Checked in Chrome')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Browser - Checked in IE11')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Browser - Checked in IE10')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Browser - Checked in IE9')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Locations',N'Browser - Checked in IE8')
		--Issue Types
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Issue Types',N'Monetary value questions are inconsistent or non-functional')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Issue Types',N'Error in choice of creation of new issue types versus modification of shared issue types')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Issue Types',N'Error in issue type visibility (dataprivacy or nondataprivacy)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Issue Types',N'Error in "zero" in language when a package with translations was cloned')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Issue Types',N'Error in visibility to online/contact center and internal reporters ')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Issue Types',N'Reporting page showing both relationship question and "Are you an employee" question.')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Issue Types',N'Error in anonymity flagging')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Issue Types',N'Typo in issue title (English)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Issue Types',N'Typo in issue description (English)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Issue Types',N'Error in customizations at the package level when using shared issue types')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Issue Types',N'Customization to closing statement not present on all issue types')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Issue Types',N'Customization to emergency statement not present on all issue types')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Issue Types',N'Customization to detail box description not present on all issue types')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Issue Types',N'Customization to detail box example/tip not present on all issue types')
		--Custom Questions
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Custom Questions',N'Missing question on one issue type')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Custom Questions',N'Default question not removed when replaced with custom version')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Custom Questions',N'Monetary value questions are inconsistent or non-functional')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Custom Questions',N'English question text different on one issue type (unless by design)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Custom Questions',N'Requirement on question incorrect')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Custom Questions',N'Question missing "Statistic Package" where needed (most commonly on relationship question)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Custom Questions',N'Question duplicated')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Custom Questions',N'Missing "Short Question (for admins)"')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Custom Questions',N'Question options incorrect')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Custom Questions',N'Questions erroneously copied to inquiry issue type')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Custom Questions',N'Questions which should have been restricted to one package were visible to others')
		--GoLive
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Typo in intake site, violations, categories, or questions')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Error in locking of locations on the issue package')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Error in use of PSO instructions with regard to locking locations ')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Incorrect phone number based on TOW (Telephony Order Form) attachment in SalesForce for EP Admin, SalesForce, intake site, or attachments')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Missing attachment')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Error in flow from screen pop')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Error in flow from contact center portal')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Has both "Are you an employee" and a relationship question on the reporting page')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Did not provide links to screen pops in SF case. Should provide links to all screen pops affected or indicate all pops were modified and provide link to example')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Country translation error')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Script error which affects intake')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Script error which affects display or pop-up messages')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Follow up link or form did not have full path (for European server clients)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Web Intake Site Page visibility to search is as requested')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Only functional language links visible, unless requested by the client')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Language Redirect(s) not in place if needed')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Child tiers still marked as "demo"')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Case counter incorrect')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'If searchable, not searchable by common name variants')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Name conflict in EP admin with new GoLive resulted in other clients being hidden inappropriately')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'For clients transferring from Alertline to EthicsPoint existing URLs not directing to the EP system unless the redirect is delayed and a comment was added to the case.')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Did not list languages taken live')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Browser - Checked in Firefox')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Browser - Checked in Chrome')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Browser - Checked in IE11')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Browser - Checked in IE10')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Browser - Checked in IE9')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'GoLive',N'Browser - Checked in IE8')
		--Information Request or Scoping
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Information Request or Scoping',N'Information request or scoping did not take PSO instructions into account')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Information Request or Scoping',N'Information request or scoping did not take client structures or functions in both the live and demo systems into account')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Information Request or Scoping',N'Work done in response to problem investigation was incorrect')
		--LDB Pull
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'LDB Pull',N'LDB pull did not take PSO instructions into account')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'LDB Pull',N'LDB pull did not take client structures or functions in both the live and demo systems into account')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'LDB Pull',N'Did not capture both parent and child LDBs if needed')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'LDB Pull',N'Did not replace redirectclientid with tier name on LDB spreadsheet')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'LDB Pull',N'Did not include all fields mentioned in the "LDB Pull Instructions" document in Confluence')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'LDB Pull',N'Did not delete columns for fields not passed to cases UNLESS those fields are needed for scripts to work')
		--Translation Spreadsheet Pull
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Spreadsheet Pull',N'Did not set case Priority to "Critical" when sending the case to QA.')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Spreadsheet Pull',N'Did not check for outstanding tasks for client that may impact translations.')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Spreadsheet Pull',N'Did not copy all relevant html or js files to a local folder -  to pull text from')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Spreadsheet Pull',N'Missed information for client with multiple violation packages')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Spreadsheet Pull',N'Missed custom questions found on all issue types')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Spreadsheet Pull',N'Missed custom questions found on only some issue types')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Spreadsheet Pull',N'Did not follow process of creating master')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Spreadsheet Pull',N'Left duplicate lines on spreadsheet')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Spreadsheet Pull',N'Left typos in text')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Spreadsheet Pull',N'Included text not usually translated')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Spreadsheet Pull',N'Missed text needed for shared dialing/DP scripts')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Spreadsheet Pull',N'Referred to the wrong form of Serbian (Cyrillic or Latin)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Spreadsheet Pull',N'Referred to the wrong form of Spanish, French, Portuguese, or Chinese')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Spreadsheet Pull',N'Languages needed were not added to spreadsheet')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Spreadsheet Pull',N'Languages needed were not added to SF case')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Spreadsheet Pull',N'Missing text')
		--Translation Upload
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Found English on translated site for instances where translated text should have appeared')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Incorrect  "select/copy/paste" resulting in stray English letters')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Error in formatting')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Typo in issue title')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Typo in WIS text')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Truncation of issue title')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Truncation of WIS text')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Languages uploaded to wrong qui')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'English issue title customized on the package, but related translation not uploaded so dropping through to non-custom translations on the issue type.')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Text replace script did not work on one language')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Question translation missing')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Question translation truncated')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Question translation wrong language')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Question option translations wrong language')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Help tips visible in English are not visible in translation')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Conditionally visible text not translated')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Error in script language reference (ciLang, ciTrans, etc.)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Follow-up links go to wrong language')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'ALL issue types displaying as English on custom issue selection page')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Missing translation on issue selection pages')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Incorrect language for attachment')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Form of Serbian (Cyrillic or Latin) is incorrect')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Case did not list all affected languages')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Browser - Checked in Firefox')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Browser - Checked in Chrome')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Browser - Checked in IE11')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Browser - Checked in IE10')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Browser - Checked in IE9')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation Upload',N'Browser - Checked in IE8')
		--Translation LANGUAGES
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Albanian (SQ)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Amharic (AM)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Arabic (AR)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Armenian (HY)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Azerbaijani (AZ)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Belarusian (BE)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Bengali (BN)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Bosnian (BS)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Bulgarian (BG)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Burmese (MY)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Chinese (Simplified) [Mainland/Mandarin] (ZHS)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Chinese (Traditional) [HK/Southern/Cantonese] (ZH)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Croatian (HR)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Czech (CS)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Danish (DA)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Dutch (NL)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Estonian (ET)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Filipino (FIL)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Finnish (FI)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'French (Canada) (FRCA)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'French (France) (FR)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Georgian (KA)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'German (DE)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Greek (GR)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Gujarati (GU)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Hebrew (HE)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Hindi (HI)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Hmong (HMN)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Hungarian (HU)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Icelandic (IS)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Indonesian (ID)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Italian (IT)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Japanese (JA)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Kannada (KN)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Kazakh (KK)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Khmer (KM)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Korean (KO)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Lao (LO)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Latvian (LV)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Lithuanian (LT)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Macedonian (MK)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Malay (MS)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Malayalam (ML)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Marathi (MR)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Mongolian (MN)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Nepali (NE)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Norwegian (NO)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Polish (PL)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Portuguese (Brazil) (PT)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Portuguese (European Union) (PTEU)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Romanian (RO)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Russian (RU)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Serbian [Cyrillic] (SR)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Serbian [Latin] (SRCS)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Sinhala (SI)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Slovak (SK)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Slovenian (SL)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Spanish (Latin American) (ES)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Spanish (European Union) (ESEU)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Swahili (KE)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Swedish (SV)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Tagalog (TL)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Tajik (TG)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Tamil (TA)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Telugu (TE)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Thai (TH)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Turkish (TR)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Ukrainian (UK)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Urdu (UR)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Uzbek (UZ)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Vietnamese (VI)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Xhosa (XH)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Translation LANGUAGES',N'Zulu (ZU)')
		--Web Site Redesign
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Redesign',N'Typo')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Redesign',N'Incorrect functionality for making a report, asking a question')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Redesign',N'Follow up link or form did not have full path (for European server clients)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Redesign',N'Data Privacy flow or restrictions are incorrect')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Redesign',N'Error in locking of locations on the issue package')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Redesign',N'Error in use of PSO instructions with regard to locking locations ')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Redesign',N'Error in attachments')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Redesign',N'Error in telephony compared with TOW attachment in SalesForce')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Redesign',N'Package change was not copied to all children (if relevant) or did not add note in PSO instructions explaining why children have different package than parent.')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Redesign',N'Did not create callcenter intake site (If needed)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Redesign',N'Browser - Checked in Firefox')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Redesign',N'Browser - Checked in Chrome')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Redesign',N'Browser - Checked in IE11')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Redesign',N'Browser - Checked in IE10')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Redesign',N'Browser - Checked in IE9')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Web Site Redesign',N'Browser - Checked in IE8')
		--Data Privacy/ Dialing Instructions
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Data Privacy/ Dialing Instructions',N'Error in display all dialing instructions in the order specified')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Data Privacy/ Dialing Instructions',N'Countries of Operation and Data Privacy flagging do not match request')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Data Privacy/ Dialing Instructions',N'Error in locking of locations on the issue package')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Data Privacy/ Dialing Instructions',N'Error in use of PSO instructions with regard to locking locations ')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Data Privacy/ Dialing Instructions',N'Error in dialing type priority for each country (ITFS vs DA, etc.)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Data Privacy/ Dialing Instructions',N'Incorrect redirects to block reporting')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Data Privacy/ Dialing Instructions',N'Incorrect redirects or alerts to show notification but  not block reporting')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Data Privacy/ Dialing Instructions',N'Incorrect pop-up alerts')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Data Privacy/ Dialing Instructions',N'Incorrect handling of anonymity')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Data Privacy/ Dialing Instructions',N'Browser - Checked in Firefox')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Data Privacy/ Dialing Instructions',N'Browser - Checked in Chrome')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Data Privacy/ Dialing Instructions',N'Browser - Checked in IE11')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Data Privacy/ Dialing Instructions',N'Browser - Checked in IE10')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Data Privacy/ Dialing Instructions',N'Browser - Checked in IE9')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Data Privacy/ Dialing Instructions',N'Browser - Checked in IE8')
		--Redesign GoLive Check
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive Check',N'Did not provide list of steps and the time needed to complete')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive Check',N'Redesign GoLive did not take PSO instructions into account.')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive Check',N'Did not take client structures or functions in both the live and demo systems into account')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive Check',N'Did not note if demo is complete in English (should check for outstanding cases)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive Check',N'Demo not built in all languages in current live system or if languages not wanted, did not provide instructions on shutting down unwanted languages')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive Check',N'Did not verify if new tiers were needed')
		--Redesign GoLive
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Did not archive all GUIs and LDB from the live tier(s)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Did not archive all GUIs and LDB from the demo/test tier(s)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Left demo clientid references in the redesign after it was taken live')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Incorrect locationids in live site after redesign taken live')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Incorrect gui files in live site after demo taken live')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Live site not using correct issue package after redesign taken live')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'PSO notes not updated after redesign taken live')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Call center flow does not match new redesign flow')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Did not remove old and unused gui files')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Did not add redirects from redesign gui slots to live site')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Typo')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Error in attachments')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Error in scripts')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Case did not list languages previously live')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Case did not list languages taken live')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Browser - Checked in Firefox')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Browser - Checked in Chrome')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Browser - Checked in IE11')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Browser - Checked in IE10')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Browser - Checked in IE9')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Browser - Checked in IE8')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Redesign GoLive',N'Steps from Redesign GoLive checklist were followed')
		--Discontinued Client
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Discontinued Client',N'In EP Admin, client was not shut down from receiving reports or remains searchable from www.ethicspoint.com')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Discontinued Client',N'Did not archive and delete intake site files in media areas and slots')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Discontinued Client',N'Did not add redirect to take reporter to issue types in main page of slots')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Discontinued Client',N'Client was findable in EP search')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Discontinued Client',N'Did not modify screen pop greeting to read, "Thank you for calling. Were sorry, but {Client name} is not accepting reports from EthicsPoint."')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Discontinued Client',N'Did not hide Make a Report and any Main page info on Screen Pop')
		--Old Dialing Instructions Update
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Old Dialing Instructions Update',N'Information from previous dialing instructions does not match new instructions, or the case does not provide a comment on why there is a mismatch')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Old Dialing Instructions Update',N'Country list from previous dialing instructions does not match new instructions, or the case does not provide a comment on why there is a mismatch')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Old Dialing Instructions Update',N'Incorrect AT&T access codes in non-shared scripts')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Old Dialing Instructions Update',N'Incorrect use of shared ITFS lines (need London ITFS information for clients using Lisbon contact center)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Old Dialing Instructions Update',N'Client with no collect calling number shows a collect option')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Old Dialing Instructions Update',N'Incorrect custom ITFS number(s)')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Old Dialing Instructions Update',N'Incorrect country redirects')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Old Dialing Instructions Update',N'Missing translations for dialing instructions')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Old Dialing Instructions Update',N'Browser - Checked in Firefox')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Old Dialing Instructions Update',N'Browser - Checked in Chrome')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Old Dialing Instructions Update',N'Browser - Checked in IE11')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Old Dialing Instructions Update',N'Browser - Checked in IE10')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Old Dialing Instructions Update',N'Browser - Checked in IE9')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Old Dialing Instructions Update',N'Browser - Checked in IE8')
		--Report Form Text Edit - English
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Report Form Text Edit - English',N'Incorrect edit')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Report Form Text Edit - English',N'Typo introduced by edit')
		--Report Form Text Edit - non-English
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Report Form Text Edit - non-English',N'Incorrect edit')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Report Form Text Edit - non-English',N'Typo introduced by edit')
		--Report Form Edits to Functionality or Look and Feel
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Report Form Edits to Functionality or Look and Feel',N'Edit did not match request')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Report Form Edits to Functionality or Look and Feel',N'Edit introduced script error')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Report Form Edits to Functionality or Look and Feel',N'Edit introduced display issue')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Report Form Edits to Functionality or Look and Feel',N'Browser - Checked in Firefox')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Report Form Edits to Functionality or Look and Feel',N'Browser - Checked in Chrome')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Report Form Edits to Functionality or Look and Feel',N'Browser - Checked in IE11')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Report Form Edits to Functionality or Look and Feel',N'Browser - Checked in IE10')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Report Form Edits to Functionality or Look and Feel',N'Browser - Checked in IE9')
		INSERT INTO [$(CastleBlack)].[NightsWatch].[Checklists]([Category],[ChecklistName]) VALUES (N'Report Form Edits to Functionality or Look and Feel',N'Browser - Checked in IE8')
COMMIT TRAN

