//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleBlackApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseItem
    {
        public long Id { get; set; }
        public string SalesForce_Case_ID { get; set; }
        public System.DateTime SalesForce_Due_Date { get; set; }
        public int Developer_ID { get; set; }
        public int QA_ID { get; set; }
        public System.DateTime Create_Dttm { get; set; }
        public System.DateTime LastUpdateDttm { get; set; }
    }
}
