//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleBlackApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseItemsLog
    {
        public long LogId { get; set; }
        public System.DateTime LogDtTm { get; set; }
        public int SalesForce_Case_ID { get; set; }
        public int Developer_ID { get; set; }
        public int QA_ID { get; set; }
        public string Event { get; set; }
    }
}
